import { nanoid } from "nanoid";
import { Product } from "../types";
import { ProductType, ProductPlacement } from "../types/enums";

const products: Product[] = [
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Radiance Necklace",
    price: 168.76,
    img: "https://i.ibb.co/bKDgk5Z/featured-product-1.jpg",
    placement: [ProductPlacement.Featured],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Exquisite Earrings",
    price: 125.28,
    img: "https://i.ibb.co/cgs89XN/featured-product-2.jpg",
    placement: [ProductPlacement.Featured],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Delights Earrings",
    price: 323.71,
    img: "https://i.ibb.co/6XXjSfK/featured-product-3.jpg",
    placement: [ProductPlacement.Featured],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Luxury Gems Necklace",
    price: 168.76,
    img: "https://i.ibb.co/QXJ45ZF/shop-11.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Aurora Ring",
    price: 125.28,
    img: "https://i.ibb.co/FnFrWxw/shop-8.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Reflections Necklace",
    price: 620.73,
    img: "https://i.ibb.co/Dw3mkZK/shop-2.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Dreamy Infinity Ring",
    price: 327.71,
    img: "https://i.ibb.co/H47sDZP/shop-6.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Opulent Jewels Ring",
    price: 168.76,
    img: "https://i.ibb.co/Q9HqdFK/shop-4.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Serene Solitaire Earrings",
    price: 125.28,
    img: "https://i.ibb.co/3m834Wz/shop-5.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Timeless Halo Earrings",
    price: 620.73,
    img: "https://i.ibb.co/mJKZ7WT/shop-3.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Exquisite Earrings",
    price: 327.71,
    img: "https://i.ibb.co/s3yMzMF/shop-10.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Sparkling Ring",
    price: 450.89,
    img: "https://i.ibb.co/cYTp3dk/shop-9.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Luxury Charms Bracelet",
    price: 620.73,
    img: "https://i.ibb.co/MG7X057/shop-12.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Blissful Bloom Ring",
    price: 348.89,
    img: "https://i.ibb.co/RjhmwZ4/shop-7.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Timeless Elegance Ring",
    price: 168.76,
    img: "https://i.ibb.co/DYr7wC4/shop-13.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Glimmering Ring",
    price: 515.35,
    img: "https://i.ibb.co/bbX1QL2/shop-1.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Shimmering Ring",
    price: 250.72,
    img: "https://i.ibb.co/jwTXrjQ/our-selection-product-1.jpg",
    placement: [ProductPlacement.Selection, ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Exquisite Earrings",
    price: 124.38,
    img: "https://i.ibb.co/2PKL4gz/our-selection-product-2.jpg",
    placement: [ProductPlacement.Selection, ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Elegance Earrings",
    price: 450.89,
    img: "https://i.ibb.co/HXvfbyM/our-selection-product-3.jpg",
    placement: [ProductPlacement.Selection, ProductPlacement.Shop],
    inBusket: false,
  },
];

export default products;
