import { nanoid } from "nanoid";
import { Product } from "../types";
import { ProductType, ProductPlacement } from "../types/enums";

const products: Product[] = [
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Radiance Necklace",
    price: 168.76,
    img: "https://i.ibb.co/bKDgk5Z/featured-product-1.jpg",
    placement: [ProductPlacement.Featured],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Refined Earrings",
    price: 125.28,
    img: "https://i.ibb.co/cgs89XN/featured-product-2.jpg",
    placement: [ProductPlacement.Featured],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Delights Earrings",
    price: 323.71,
    img: "https://i.ibb.co/6XXjSfK/featured-product-3.jpg",
    placement: [ProductPlacement.Featured],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Luxury Gems Necklace",
    price: 168.76,
    img: "https://i.ibb.co/QXJ45ZF/shop-11.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Aurora Bracelet",
    price: 125.28,
    img: "https://i.ibb.co/FnFrWxw/shop-8.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Reflections Bracelet",
    price: 228.75,
    img: "https://i.ibb.co/Dw3mkZK/shop-2.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Dreamy Infinity Ring",
    price: 327.71,
    img: "https://i.ibb.co/H47sDZP/shop-6.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Opulent Jewels Ring",
    price: 168.76,
    img: "https://i.ibb.co/Q9HqdFK/shop-4.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Serene Solitaire Earrings",
    price: 125.28,
    img: "https://i.ibb.co/3m834Wz/shop-5.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Ornate Earrings",
    price: 802.49,
    img: "https://i.ibb.co/qpJWCZf/shop-31.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Timeless Halo Earrings",
    price: 620.73,
    img: "https://i.ibb.co/mJKZ7WT/shop-3.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Sparkling Ring",
    price: 450.89,
    img: "https://i.ibb.co/cYTp3dk/shop-9.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Graceful Earrings",
    price: 124.38,
    img: "https://i.ibb.co/s3yMzMF/shop-10.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Luxury Charms Bracelet",
    price: 620.73,
    img: "https://i.ibb.co/MG7X057/shop-12.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Blissful Bloom Ring",
    price: 348.89,
    img: "https://i.ibb.co/RjhmwZ4/shop-7.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Marvelous Bracelet",
    price: 942.16,
    img: "https://i.ibb.co/QDfhycK/shop-29.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Timeless Elegance Ring",
    price: 168.76,
    img: "https://i.ibb.co/DYr7wC4/shop-13.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Glimmering Ring",
    price: 515.35,
    img: "https://i.ibb.co/bbX1QL2/shop-1.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Shimmering Ring",
    price: 250.72,
    img: "https://i.ibb.co/jwTXrjQ/our-selection-product-1.jpg",
    placement: [ProductPlacement.Selection, ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Exquisite Earrings",
    price: 327.71,
    img: "https://i.ibb.co/2PKL4gz/our-selection-product-2.jpg",
    placement: [
      ProductPlacement.Selection,
      ProductPlacement.Shop,
      ProductPlacement.Collection,
    ],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Elegance Earrings",
    price: 620.73,
    img: "https://i.ibb.co/HXvfbyM/our-selection-product-3.jpg",
    placement: [
      ProductPlacement.Selection,
      ProductPlacement.Shop,
      ProductPlacement.Collection,
    ],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Palatial Jewels Ring",
    price: 168.76,
    img: "https://i.ibb.co/J2WW6N9/collection-1.jpg",
    placement: [ProductPlacement.Collection],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Serene Solitaire Ring",
    price: 125.28,
    img: "https://i.ibb.co/0QGL94f/collection-2.jpg",
    placement: [ProductPlacement.Shop, ProductPlacement.Collection],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Brooch,
    name: "Timeless Brooch",
    price: 204.54,
    img: "https://i.ibb.co/LNrTNFg/collection-3.jpg",
    placement: [ProductPlacement.Collection],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Lavish Ring",
    price: 450.89,
    img: "https://i.ibb.co/rcd8trw/shop-17.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Luxurious Ring",
    price: 250.72,
    img: "https://i.ibb.co/NNd20kP/shop-16.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Deluxe Emerald Necklace",
    price: 1015.99,
    img: "https://i.ibb.co/dpf7Tfn/shop-14.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Dedicated Rubin Ring",
    price: 802.49,
    img: "https://i.ibb.co/VpCqLgh/shop-23.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Sparkling Necklace",
    price: 515.35,
    img: "https://i.ibb.co/G0Z16FK/collection-5.jpg",
    placement: [ProductPlacement.Shop, ProductPlacement.Collection],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Glimmering Earrings",
    price: 450.89,
    img: "https://i.ibb.co/zQCLKfM/collection-6.jpg",
    placement: [ProductPlacement.Shop, ProductPlacement.Collection],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Splendid Earrings",
    price: 780.99,
    img: "https://i.ibb.co/mDbJZrz/shop-30.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Extraordinary Bracelet",
    price: 150.25,
    img: "https://i.ibb.co/TLyY6JC/shop-28.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Magnificent Necklace",
    price: 1010.99,
    img: "https://i.ibb.co/b121nPh/shop-15.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Elaborate Earrings",
    price: 204.54,
    img: "https://i.ibb.co/vJHJsry/shop-18.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Sophisticated Necklace",
    price: 327.71,
    img: "https://i.ibb.co/qnGvBxR/shop-19.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Grand Necklace",
    price: 168.76,
    img: "https://i.ibb.co/Yd5wcvC/shop-21.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Astonishing Bracelet",
    price: 89.99,
    img: "https://i.ibb.co/8c1QC7W/shop-26.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Earring,
    name: "Exclusive Earrings",
    price: 250.72,
    img: "https://i.ibb.co/r4GyGGG/shop-22.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Ring,
    name: "Luxury Ring",
    price: 450.89,
    img: "https://i.ibb.co/WBBxxbb/collection-4.jpg",
    placement: [ProductPlacement.Shop, ProductPlacement.Collection],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Recherche Necklace",
    price: 780.99,
    img: "https://i.ibb.co/BPS2bbr/shop-24.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Necklace,
    name: "Sumptuous Necklace",
    price: 204.54,
    img: "https://i.ibb.co/YR97Gx7/shop-25.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Fanciful Bracelet",
    price: 125.28,
    img: "https://i.ibb.co/RjWBcfQ/shop-20.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
  {
    id: nanoid(),
    type: ProductType.Bracelet,
    name: "Resplendent Bracelet",
    price: 450.89,
    img: "https://i.ibb.co/XfRcqTM/shop-27.jpg",
    placement: [ProductPlacement.Shop],
    inBusket: false,
  },
];

export default products;
